<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFrameworks>netstandard2.0;net8.0-windows</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <RollForward>LatestMajor</RollForward>
    <DebugType>portable</DebugType>
    <DebugSymbols>True</DebugSymbols>

    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <EmitCompilerGeneratedFiles Condition="'$(Configuration)' == 'Debug'">True</EmitCompilerGeneratedFiles>

    <AnalysisMode>recommended</AnalysisMode>
    <AnalysisModePerformance>all</AnalysisModePerformance>
    <AnalysisModeInteroperability>none</AnalysisModeInteroperability>
  </PropertyGroup>

  <PropertyGroup>
    <RootNamespace>SegEx</RootNamespace>

    <GeneratePackageOnBuild Condition="'$(Configuration)' == 'Release'">True</GeneratePackageOnBuild>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <IncludeSymbols>True</IncludeSymbols>
    <Version>$(CoreVersion)</Version>

    <PackageId>$(AssemblyName)</PackageId>
    <PackageVersion>$(Version)</PackageVersion>
    <PackageDescription>Regex matching with familiar perf on segmented/multipart subjects.</PackageDescription>
    <PackageRequireLicenseAcceptance>False</PackageRequireLicenseAcceptance>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>

    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/jolaquai/$(AssemblyName)</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\LICENSE;..\README.md" Pack="True" PackagePath="/" />

    <Using Include="System.Diagnostics" />

    <Using Include="System.Runtime.CompilerServices" />
    <Using Include="System.Runtime.InteropServices" />

    <Using Include="System.Text" />
    <Using Include="System.Text.RegularExpressions" />

    <ProjectReference Include="..\SegEx.SourceGen\SegEx.SourceGen.csproj" ReferenceOutputAssembly="false" SetTargetFramework="TargetFramework=$(TargetFramework)" />
  </ItemGroup>

  <Import Project="$(MSBuildProjectDirectory)\_PackSourceGen.targets" />

  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
    <Compile Remove="**/*.net.cs" />
    <None Include="**/*.net.cs" />
    <PackageReference Include="System.Memory" Version="4.6.3" />
    <PackageReference Include="Microsoft.Bcl.HashCode" Version="6.0.0" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' != 'netstandard2.0'">
    <Compile Remove="**/*.netstandard2.0.cs" />
    <None Include="**/*.netstandard2.0.cs" />
  </ItemGroup>
  <PropertyGroup Condition="'$(TargetFramework)' == 'net8.0-windows'">
    <IsAotCompatible>True</IsAotCompatible>
  </PropertyGroup>

</Project>
